import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import Image from 'next/image'

import MoneyInput from '@/components/MoneyInput'
import { useState } from 'react'





export default function Home() {
  const [valueA, setValueA] = useState("");
  const [valueB, setValueB] = useState("");
  const [currencySelectedA, setCurrencySelectedA] = useState("USD");
  const [currencySelectedB, setCurrencySelectedB] = useState("BRL");


  function autoCurrency(amount = "1") {

    var myHeaders = new Headers();
    myHeaders.append("apikey", process.env.NEXT_PUBLIC_API_KEY);
    var requestOptions = {
      method: 'GET',
      redirect: 'follow',
      headers: myHeaders
    };

    fetch(`https://api.apilayer.com/currency_data/convert?to=${currencySelectedB}&from=${currencySelectedA}&amount=${parseFloat(amount)}`, requestOptions)
      .then(response => response.json())
      .then(result => setValueB(JSON.stringify(result.result)))
      .catch(error => console.log('error', error));
    console.log("currency: ", currencySelectedA + " " + parseFloat(valueB).toFixed(2));

  }

  function switchCurrency() {

    setCurrencySelectedA(currencySelectedB)
    setCurrencySelectedB(currencySelectedA)
    setValueA("0.00")
    setValueB("0.00")
    
  }

  return (
    <>
      <Head>
        <title>Bora Codar 09</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />


      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.topContainer}>
            <h1>Conversor de moedas</h1>

            <nav className={styles.navContainer}>
              <MoneyInput currency="BR" setCurrencyInput={setValueA} currencyInput={valueA} autoCurrency={autoCurrency} disabled={false} currencyProps="USD" setSelectedValue={setCurrencySelectedA} currencySelected={currencySelectedA} />

              <button className={styles.switchArrows} onClick={() => switchCurrency()} >
                <Image 
                  src="/images/arrows.svg"
                  alt="Picture of the author"
                  width={20}
                  height={20}
                />
              </button>

              <MoneyInput currency="UDS" setCurrencyInput={setValueB} currencyInput={valueB} autoCurrency={autoCurrency} disabled={true} currencyProps="BRL" setSelectedValue={setCurrencySelectedB} currencySelected={currencySelectedB} />
            </nav>
          </div>
          <div className={styles.mapContainer}>
            <h1>Taxa de câmbio</h1>
            <div className={styles.chart}>
              <Image
                src="/images/chart.svg"
                alt="chart"
                width={640}
                height={356}
              />
            </div>

          </div>

        </div>
      </main>
    </>
  )
}
