import Head from 'next/head';
import { useState } from 'react';
import styles from '@/styles/Home.module.css';

import Image from 'next/image';

import MoneyInput from '@/components/MoneyInput';
import Chart from '@/components/Chart';











export default function Home() {
  const [valueA, setValueA] = useState("");
  const [valueB, setValueB] = useState("");
  const [currencySelectedA, setCurrencySelectedA] = useState("USD");
  const [currencySelectedB, setCurrencySelectedB] = useState("BRL");


  function autoCurrency(amount = "1") {

    var myHeaders = new Headers();
    myHeaders.append("apikey", process.env.NEXT_PUBLIC_API_KEY);
    var requestOptions = {
      method: 'GET',
      redirect: 'follow',
      headers: myHeaders
    };

    fetch(`https://api.apilayer.com/currency_data/convert?to=${currencySelectedB}&from=${currencySelectedA}&amount=${parseFloat(amount)}`, requestOptions)
      .then(response => response.json())
      .then(result => setValueB(JSON.stringify(result.result)))
      .catch(error => console.log('error', error));
    console.log("currency: ", currencySelectedA + " " + parseFloat(valueB).toFixed(2));

  }

  function switchCurrency() {

    setCurrencySelectedA(currencySelectedB)
    setCurrencySelectedB(currencySelectedA)
    setValueA("0.00")
    setValueB("0.00")

  }

  return (
    <>
      <Head>
        <title>Bora Codar 09</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.6.6/css/flag-icons.min.css"
        />


      </Head>
      <main className={styles.main}>

        <section className={styles.conversor}>
          <h2>Conversor de moedas</h2>
          <div className={styles.wrapper}>
            <MoneyInput currency="BR" setCurrencyInput={setValueA} currencyInput={valueA} autoCurrency={autoCurrency} disabled={false} currencyProps="USD" setSelectedValue={setCurrencySelectedA} currencySelected={currencySelectedA} />

            <button className={styles.switchArrows} onClick={() => switchCurrency()} >
              <Image
                src="/images/arrows.svg"
                alt="Picture of the author"
                width={20}
                height={20}
              />
            </button>

            <MoneyInput currency="UDS" setCurrencyInput={setValueB} currencyInput={valueB} autoCurrency={autoCurrency} disabled={true} currencyProps="BRL" setSelectedValue={setCurrencySelectedB} currencySelected={currencySelectedB} />
          </div>
        </section>
        <section className={styles.cambio}>
          <h2>Taxa de câmbio</h2>
          <div className={styles.wrapper}>
            <Chart />
            <div className={styles.chartControls}>
                <button>1D</button>
                <button>5D</button>
                <button>1M</button>
                <button>1A</button>
                <button>5A</button>
                <button>Máx</button>
            </div>

          </div>

        </section>


      </main>
    </>
  )
}
